## Debug info:
message(STATUS "GLM_ROOT: ${GLM_ROOT}")
message(STATUS "	GLM_INCLUDE_DIRS: ${GLM_INCLUDE_DIRS}")

message(STATUS "BOOST_ROOT: ${BOOST_ROOT}")
message(STATUS "    Boost_FOUND: ${Boost_FOUND}")
message(STATUS "    Boost_VERSION: ${Boost_VERSION}")
message(STATUS "    Boost_INCLUDE_DIRS: ${Boost_INCLUDE_DIRS}")
message(STATUS "    Boost_LIBRARIES: ${Boost_LIBRARIES}")
message(STATUS "    Boost_LIBRARY_DIRS: ${Boost_LIBRARY_DIRS}")

message(STATUS "SDL2_ROOT: ${SDL2_DIR}")
message(STATUS "	SDL2_INCLUDE_DIR: ${SDL2_INCLUDE_DIR}")
message(STATUS "	SDL2_DEFINITIONS: ${SDL2_DEFINITIONS}")
message(STATUS "	SDL2_LIBRARIES: ${SDL2_LIBRARIES}")

message(STATUS "GLEW_ROOT: ${GLEW_ROOT}")
message(STATUS "	GLEW_INCLUDE_DIRS: ${GLEW_INCLUDE_DIRS}")
message(STATUS "	GLEW_LIBRARY_DIRS: ${GLEW_LIBRARY_DIRS}")
message(STATUS "	GLEW_DEFINITIONS: ${GLEW_DEFINITIONS}")
message(STATUS "    GLEW_LIBRARIES: ${GLEW_LIBRARIES}")

message(STATUS "OpenGL: ")
message(STATUS "	OpenGL_INCLUDE_DIRS: ${OpenGL_INCLUDE_DIRS}")
message(STATUS "	OpenGL_LIBRARY_DIRS: ${OpenGL_LIBRARY_DIRS}")
message(STATUS "	OpenGL_DEFINITIONS: ${OpenGL_DEFINITIONS}")

message(STATUS "USED CXX Flags: ${CMAKE_CXX_FLAGS}")

message(STATUS "Possible CXX_FLAGS for platform: ")
message("       CMAKE_CXX_FLAGS_DEBUG is ${CMAKE_CXX_FLAGS_DEBUG}")
message("       CMAKE_CXX_FLAGS_RELEASE is ${CMAKE_CXX_FLAGS_RELEASE}")
message("       CMAKE_CXX_FLAGS_RELWITHDEBINFO is ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
message("       CMAKE_CXX_FLAGS_MINSIZEREL is ${CMAKE_CXX_FLAGS_MINSIZEREL}")
